/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#87cda3c8c1fac6010df8cac4edb5bd0d1e36ad5e
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto;
import { re } from '@bablr/boot';
import { eat } from '@bablr/helpers/grammar';
import { Node } from '@bablr/helpers/decorators';
export const canonicalURL = 'https://bablr.org/languages/core/en/plain-text';
export const grammar = class BlankSpaceGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Text"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *Text() {
    yield eat(re`/./s`);
  }
};